spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  mustache:
    cache: false
  session:
    store-type: jdbc
  profiles:
    include: oauth
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: test
#            client-secret: test
#            scope: email, profile

server:
  port: 80
