<<<<<<< HEAD
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 291568483413-9nhg71oek1ncq2o7dfln5225mvomokhb.apps.googleusercontent.com
            client-secret: zoSXqQPu8EgtbooDXWKJEyF1
            scope: email, profile
          naver:
            client-id: cFe55kP3_j6RYs5y1jAV
            client-secret: 4ocCNEA5DL
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
=======
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 291568483413-9nhg71oek1ncq2o7dfln5225mvomokhb.apps.googleusercontent.com
            client-secret: zoSXqQPu8EgtbooDXWKJEyF1
            scope: email, profile
          naver:
            client-id: cFe55kP3_j6RYs5y1jAV
            client-secret: 4ocCNEA5DL
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
>>>>>>> origin/master
